# Copyright 2016 Mycroft AI Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from os.path import dirname
from adapt.intent import IntentBuilder
from mycroft.messagebus.message import Message
from mycroft.skills.core import MycroftSkill, intent_handler, intent_file_handler
import os
import time


class StopSkill(MycroftSkill):
    def __init__(self):
        super().__init__(name="StopSkill")

    @intent_handler(IntentBuilder("").require("Stop"))
    def handle_stop(self, event):
        # Framework catches this, invokes stop() method on all skills
        self.bus.emit(Message("mycroft.stop"))

    ######################################################################
    # Typically the enclosure will handle all of the following
    # NOTE: system.update is generated by skill-version-checker
    ######################################################################

    @intent_file_handler("reboot.intent")
    def handle_reboot(self, event):
        if self.ask_yesno("confirm.reboot") == "yes":
            os.system("mycroft-stop")
            time.sleep(10)
            os.system("systemctl reboot")

    @intent_file_handler("shutdown.intent")
    def handle_shutdown(self, event):
        if self.ask_yesno("confirm.shutdown") == "yes":
            os.system("mycroft-stop")
            time.sleep(10)
            os.system("systemctl poweroff")

    @intent_file_handler('skill_reboot.intent')
    def handle_skill_reboot(self, event):
        os.system("mycroft-stop && mycroft-start all")

    @intent_file_handler('skill_reboot_cli.intent')
    def handle_skill_reboot_cli(self, event):
        os.system("mycroft-stop && mycroft-start all && mycroft-cli-client")

def create_skill():
    return StopSkill()
